<?php
/** @var \SaberSmesem\MageBlog\Block\Template $block */

/** here you can get block class object by "$this" or "$block"  **/
/** here i'll use "$block" for get block object **/

// get collection which we set in block class
$_posts = $block->getCollection();
?>

<div class="page-main">
    <h1>
        <?php
        //$block->getMageBlog()
        ?>
    </h1>

    <div class="post-list-wrapper">
        <?php if ($_posts && count($_posts)): ?>
        <ul class="post-list">
            <?php  // read collection as magento1.x and display in list
            foreach ($_posts as $_post): ?>
            <li class="post-holder post-holder-5">
                <div class="post-header">
                    <div class="post-title-holder clearfix">
                        <h2 class="post-title">
                            <a class="post-item-link" href="<?= $block->getUrl('mageblog/post/detail', ['id' => $_post->getId()]) ?>">
                                <?=$_post->getTitle()?>
                            </a>
                        </h2>
                    </div>
                    <div class="post-info">
                        <div class="item post-posted-date">
                            <i class="mf-blog-icon mfbi-calendar"></i>
                            <span class="label">Posted:</span>
                            <span class="value"><?=$_post->getCreatedAt()?></span>
                        </div>
                        &nbsp;&nbsp;
                        <div class="item post-categories">
                            <i class="mf-blog-icon mfbi-folder"></i>
                            <span class="label">Categories:</span>
                            <a title="Magento 2" href="javascript:void(0)">Magento 2</a>,
                            <a title="Tutorials" href="javascript:void(0)">Tutorials</a>
                        </div>
                    </div>
                </div>
                <div class="post-content">
                    <div class="post-description clearfix">
                        <div class="post-ftimg-hld">
                            <a href="#" title="<?=$_post->getTitle()?>">
                                <img src="<?=$this->getViewFileUrl('SaberSmesem_MageBlog::images/posts/'.$_post->getFeaturedImage());?>" alt="<?=$_post->getTitle()?>">
                            </a>
                        </div>
                    </div>
                    <div class="post-text-hld">
                        <div data-content-type="html" data-appearance="default" data-element="main" data-decoded="true">
                            <p>
                                <?php
                                    $post_content_excerpt = mb_substr($_post->getContent(), 0, 250, 'UTF-8');
                                    echo $post_content_excerpt;
                                ?>

                                
                                <?php if(strlen($_post->getContent()) > 50) echo '...'; ?>
                            </p>
                            <p></p>
                        </div>
                        <a class="post-read-more" href="#" title="<?=$_post->getTitle()?>">
                            Read more »
                        </a>
                    </div>

                </div>
                <div class="post-footer dotted"></div>
            </li>
            <?php endforeach; ?>
        </ul>

        <!-- Pager -->
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom">
                <?php 
                // for display pager block which we create in block file.
                echo $block->getPagerHtml();
                ?>
            </div>
        <?php endif ?>

        <?php else: ?>
            <div class="message info empty">
                <span><?php echo __('No posts available.'); ?></span>
            </div>
        <?php endif ?>
    </div>
</div>